// Auto-generated by export-abi.sh
// DO NOT EDIT MANUALLY

import MockXAUT from "./MockXAUT.json";
import IDRX from "./IDRX.json";
import MockPriceOracle from "./MockPriceOracle.json";
import CollateralManager from "./CollateralManager.json";
import LoanManager from "./LoanManager.json";
import AuRoomProtocol from "./AuRoomProtocol.json";

// Base Sepolia deployed addresses
export const ADDRESSES = {
  MockXAUT: "0x2396937B0dEDDb940f759b89CDeb93aB338f9b7D",
  IDRX: "0x94c3E30DFfA76418Ab8c9eAb2e7Dd2f96DE1b2bF",
  MockPriceOracle: "0x6942C3a773496925D54Afd8b0fF8c2F1cCfC75EC",
  CollateralManager: "0xba3ACdCf0B0965162b78Ab87Fa42a2074eE4F846",
  LoanManager: "0x85A5A711D7ac9bd88F1AFB02c6Ecd089Be4FDA56",
  AuRoomProtocol: "0x297a97c81B0D6A47afC20C4164D20dCFcEF77e0E",
} as const;

// ABIs
export const ABIS = {
  MockXAUT,
  IDRX,
  MockPriceOracle,
  CollateralManager,
  LoanManager,
  AuRoomProtocol,
} as const;

// Chain configuration
export const CHAIN_CONFIG = {
  id: 84532,
  name: "Base Sepolia",
  rpcUrl: "https://sepolia.base.org",
  blockExplorer: "https://sepolia.basescan.org",
} as const;

// Protocol constants (from smart contract)
export const PROTOCOL_CONFIG = {
  LTV_BPS: 5000, // 50%
  LIQUIDATION_THRESHOLD_BPS: 8000, // 80%
  ANNUAL_INTEREST_RATE_BPS: 800, // 8%
  LIQUIDATION_PENALTY_BPS: 100, // 1%
  MIN_BORROW: 1000000, // 10,000 IDRX (2 decimals)
  XAUT_DECIMALS: 6,
  IDRX_DECIMALS: 2,
  PRICE_DECIMALS: 6,
} as const;
